require File.expand_path(File.dirname(__FILE__) + '/feature_selection/log_helpers')
require File.expand_path(File.dirname(__FILE__) + '/feature_selection/base')
require File.expand_path(File.dirname(__FILE__) + '/feature_selection/job')
require File.expand_path(File.dirname(__FILE__) + '/feature_selection/algorithms/mutual_information')
require File.expand_path(File.dirname(__FILE__) + '/feature_selection/algorithms/chi_squared')
require File.expand_path(File.dirname(__FILE__) + '/feature_selection/algorithms/frequency_based')